-- 回滚 000001_init_schema
-- 按依赖逆序 DROP 全部表与类型

DROP TABLE IF EXISTS moment_comments CASCADE;
DROP TABLE IF EXISTS moment_likes CASCADE;
DROP TABLE IF EXISTS moment_images CASCADE;
DROP TABLE IF EXISTS moments CASCADE;
DROP TABLE IF EXISTS ai_search_references CASCADE;
DROP TABLE IF EXISTS ai_messages CASCADE;
DROP TABLE IF EXISTS ai_sessions CASCADE;
DROP TABLE IF EXISTS audio_transcriptions CASCADE;
DROP TABLE IF EXISTS creation_submissions CASCADE;
DROP TABLE IF EXISTS creation_tasks CASCADE;
DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS node_submissions CASCADE;
DROP TABLE IF EXISTS node_progress CASCADE;
DROP TABLE IF EXISTS node_contents CASCADE;
DROP TABLE IF EXISTS class_nodes CASCADE;
DROP TABLE IF EXISTS class_members CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS touch_updated_at() CASCADE;

DROP TYPE IF EXISTS activity_status CASCADE;
DROP TYPE IF EXISTS resource_media_type CASCADE;
DROP TYPE IF EXISTS ai_message_role CASCADE;
DROP TYPE IF EXISTS audio_trans_status CASCADE;
DROP TYPE IF EXISTS chat_finish_reason CASCADE;
DROP TYPE IF EXISTS creation_status CASCADE;
DROP TYPE IF EXISTS creation_task_type CASCADE;
DROP TYPE IF EXISTS scene_type CASCADE;
DROP TYPE IF EXISTS node_type CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
